# Pytorch Tutorial

### 2. Modules and Custom Models

- Adding predefined modules from ```torch.nn``` to ```torch.nn.Sequential```.
- Creating custom models by inheriting ```torch.nn.Module```.

Some setup.

```torch.nn``` is conventionally imported as ```nn```.  
```torch.nn.functional``` is conventionally imported as ```F```.

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

## Using ```torch.nn``` modules and ```torch.nn.Sequential```

There are many predefined layers in ```torch.nn```, like conv, linear, pool, ReLU, and more. Also, there are many predefined functions in ```torch.nn.functional```, which overlap a lot with those in ```torch.nn```. The functions are listed in [the Pytorch documentation](https://pytorch.org/docs/stable/nn.html).

The difference is that those defined in ```torch.nn``` are essentially wrappers of functions in ```torch.nn.functional``` plus weight initialization and functions such as ```train()```, ```eval()```, or ```parameters()```. Functionals only compute the bare computation of the layer.

Here we instantiate a simple two dimensional convolution layer and run it.

In [2]:
X = torch.randn((64, 3, 23, 23))

In [3]:
two_dimensional_conv = nn.Conv2d(in_channels=3, out_channels=64, kernel_size=11, stride=4, padding=2)
two_dimensional_conv(X)

tensor([[[[ 0.3242, -0.0299,  0.5053,  0.1944,  0.5568],
          [ 0.4473, -0.7854,  0.0498,  0.6596,  0.5347],
          [-1.1333, -0.4399, -0.2280,  0.8520, -0.2446],
          [ 0.6046, -0.9033,  1.0315, -0.7924, -0.2479],
          [ 0.2334,  0.8097, -0.6301,  0.5498,  0.3982]],

         [[ 0.0656,  1.2447,  0.3868,  0.5862, -0.4954],
          [ 0.0801, -1.0360,  0.4003,  0.1854,  0.4029],
          [ 0.1834,  0.6223,  0.7189,  0.5508, -0.0173],
          [-0.2326, -0.0663, -0.2472, -0.1819,  0.3045],
          [ 0.0031, -0.0858, -0.2253, -0.4184,  0.8533]],

         [[ 0.1784, -0.2754,  0.0795,  0.7774,  0.1876],
          [-0.7676,  1.4561,  0.5549,  0.3622, -0.2183],
          [ 0.2104, -0.4029,  0.1401, -0.9150,  0.6609],
          [ 0.1210, -0.2161, -0.4463,  0.0390, -0.5558],
          [-0.2484, -0.1759, -0.1680, -0.5349,  0.1346]],

         ...,

         [[-0.2439, -0.2298, -0.0422, -0.0121,  1.0363],
          [-0.0490,  0.9998,  0.1759,  0.6432,  0.3420],
          

Now we run the same convolution with an all-zero filter. Try to catch the difference between ```torch.nn``` layers and ```torch.nn.functional``` functions.

In [7]:
zero_conv_result = F.conv2d(input=X, weight=torch.zeros(64, 3, 11, 11), stride=4, padding=2)
zero_conv_result_pool = F.max_pool2d(zero_conv_result, kernel_size=3, stride=2)
zero_conv_result_pool

tensor([[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         ...,

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         ...,

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         ...,

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        ...,


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]],

         ...,

         [[0., 0.],
          [0., 0.

With ```nn.Sequential```, we can define simple models that do not require much setup.

In [8]:
simple_model = nn.Sequential(
    nn.Conv2d(3, 64, kernel_size=11, stride=4, padding=2),
    nn.ReLU(),
    nn.MaxPool2d(kernel_size=3, stride=2)
)

simple_model(X)

tensor([[[[0.8375, 0.3527],
          [0.0991, 0.4620]],

         [[0.7641, 0.7641],
          [0.7641, 0.7641]],

         [[0.7477, 0.6807],
          [0.7477, 0.5126]],

         ...,

         [[1.2538, 1.2538],
          [0.7319, 0.3746]],

         [[0.6574, 0.6888],
          [0.4160, 0.6888]],

         [[0.3700, 1.0302],
          [0.3234, 0.3940]]],


        [[[0.7115, 0.8124],
          [0.9468, 0.9468]],

         [[0.8445, 0.6777],
          [0.7232, 0.7027]],

         [[0.6984, 0.8395],
          [0.5988, 0.8113]],

         ...,

         [[0.4136, 0.1237],
          [1.0771, 0.4987]],

         [[1.7439, 1.7439],
          [0.5152, 1.2221]],

         [[1.1078, 1.1078],
          [0.8472, 1.0773]]],


        [[[0.8966, 0.8966],
          [0.8447, 0.7951]],

         [[0.7645, 0.8031],
          [0.8775, 0.8775]],

         [[1.5547, 1.5547],
          [1.5547, 1.5547]],

         ...,

         [[0.4454, 0.4585],
          [0.3934, 0.4585]],

         [[0.4848, 0.47

## Creating Custom Models

To create custom models, we define a class that inherits ```torch.nn.Module```. Then, all we need to define is the ```__init__``` function and the ```forward``` function.

Generally speaking, we define the layers and their initialization in ```__init__``` and define their connections in ```forward```.

In [9]:
class SimpleNet(nn.Module):
    
    def __init__(self, num_classes=10):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 64, kernel_size=11, stride=4, padding=2)
        self.pool1 = nn.MaxPool2d(kernel_size=3, stride=2)
        
        self.dropout1 = nn.Dropout(p=0.3)
        self.fc1 = nn.Linear(64*2*2, num_classes)
        
        self.convs = [nn.Conv]
        
        for m in self.modules():
            if type(m) in [nn.Conv2d, nn.Linear]:
                nn.init.kaiming_normal_(m.weight, nonlinearity='relu')
                m.bias.data.fill_(0)
    
    def forward(self, x):
        x = self.conv1(x)
        x = F.relu(x)
        x = self.pool1(x)
        x = x.view(-1, 64*2*2)
        x = self.dropout1(x)
        x = self.fc1(x)
        return x

In [10]:
model = SimpleNet()
model(X).shape

torch.Size([64, 10])